### ISSUE TITLE
Broken Links when tyring to go to brewery website from specific beer page

### ISSUE THREAD

**Issue by emtrimble** [jeffbum/ale-nomad-final-project#115]

**Comment by jeffbum** [comment]
added this line of code. not only does it link to site, but also opens a new tab!

<div>Website: <a href={this.state.breweryDetails.website} target="_blank">{this.state.breweryDetails.website}</a></div>

**Comment by jeffbum** [comment]
Added this line of code AND it opens in new tab!
<div>Website: <a href={this.state.breweryDetails.website} target="_blank">{this.state.breweryDetails.website}</a></div>
