### ISSUE TITLE
Tried to favorite a beer without having a profile set up. Nothing happened.

### ISSUE THREAD

**Issue by emtrimble** [jeffbum/ale-nomad-final-project#118]

**Comment by jeffbum** [comment]
Added this line. now you can't rate a beer if your'e not logged in!

{this.state.loggedIn ? <div>
                            <h2>Rate this Beer: {rating}</h2>
                             <StarRatingComponent name="rate1" starCount={5} value={rating} onStarClick={this.onStarClick} /></div> : <div></div>}
