### ISSUE TITLE
This should probably be a private method

### ISSUE THREAD

**Issue by dummied** [jeffbum/ale-nomad-final-project#141]
https://github.com/jeffbum/ale-nomad-final-project/blob/master/app/controllers/beers_controller.rb#L15-L23

Since it doesn't handle an http request and is instead a helper function

**Comment by dummied** [comment]
Same: https://github.com/jeffbum/ale-nomad-final-project/blob/master/app/controllers/brews_controller.rb#L13-L21

**Comment by Keilsmit** [comment]
completed (made a private method)
